// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.cache.enabled", true);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.dom.quotaManager.backgroundTask.enabled", false);
user_pref("app.normandy.user_id", "988e6593-b600-4bfd-8807-ed580d55043c");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1682507787);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1682507767);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1682507764);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1682507817);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{1b702e24-117a-4511-a884-5f5208ca0cb2}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1682507757);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 136);
user_pref("browser.newtabpage.activity-stream.impressionId", "{55b55839-1371-4fda-b93b-a42e89943817}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1682507761);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1682507781358");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1682509606358");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1682507767373");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1682529367373");
user_pref("browser.search.region", "BR");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage", "infobase.jati.com.br");
user_pref("browser.startup.homepage_override.buildID", "20230414125621");
user_pref("browser.startup.homepage_override.mstone", "112.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1682507759);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.iniFile.exists.appversion", "112.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint-001.bookmarksProcessed", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "aad8fc882d7c4effaed3d2c86b489053");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1682507759);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-CA@firefox.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-en-GB@firefox.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-pt-BR@firefox.mozilla.org", true);
user_pref("extensions.installedDistroAddon.langpack-pt-PT@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20230414125621");
user_pref("extensions.lastAppVersion", "112.0.1");
user_pref("extensions.lastPlatformVersion", "112.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"cd35e15d-4b0b-4f45-a541-1750a4134b74\",\"pictureinpicture@mozilla.org\":\"c28c842d-c66f-4c9c-ae6b-f27902389188\",\"screenshots@mozilla.org\":\"a4107953-e8a6-4eb3-b409-102ef751697f\",\"webcompat-reporter@mozilla.org\":\"6105009a-0ea5-45a0-a25e-b92a79b79a95\",\"webcompat@mozilla.org\":\"0df78f8b-2869-4e02-b8f8-c4a587ffc0bd\",\"default-theme@mozilla.org\":\"ea3e6405-f704-43c0-a883-f5f887984a82\",\"addons-search-detection@mozilla.com\":\"5bbb32f9-eb6a-4906-9c0d-c192fe00a2ec\",\"google@search.mozilla.org\":\"a5cd59be-7075-45fe-8400-5a06e20ea744\",\"wikipedia@search.mozilla.org\":\"a6009bb9-e48c-48ce-a90d-59081070ae94\",\"mercadolivre@search.mozilla.org\":\"faacebeb-dafd-4c70-b67e-dcdd460d5a73\",\"bing@search.mozilla.org\":\"31553b14-320c-4319-b25a-428d0a3b15a6\",\"ddg@search.mozilla.org\":\"8e74d63c-20d2-4950-b6cd-0d6749259297\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.accessibilityCache", "{\"slug\":\"next-generation-accessibility-engine-powering-screen-readers\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"accessibilityCache\"},\"features\":null},\"active\":true,\"enrollmentId\":\"52d5afbc-e4dc-408f-b7cb-afde7139bc60\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Next generation accessibility engine powering screen readers\",\"userFacingDescription\":\"Evaluating a major re-architecture of Firefox's accessibility engine to improve performance of screen readers and other assistive technologies.\",\"lastSeen\":\"2023-04-26T11:16:03.485Z\",\"featureIds\":[\"accessibilityCache\"],\"prefs\":[{\"name\":\"accessibility.cache.enabled\",\"branch\":\"user\",\"featureId\":\"accessibilityCache\",\"variable\":\"enabled\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.accessibilityCache.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6ffef676-2dd0-4774-850d-0b4e47b1067a");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1682507755);
user_pref("toolkit.telemetry.cachedClientID", "9dc04130-c1ee-4680-a334-e569b3ddf8d6");
user_pref("toolkit.telemetry.previousBuildID", "20230414125621");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
